/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/subtitles/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Subtitles */
        post: operations["analyze_subtitles_v1_subtitles_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeSubtitlesRequest */
        AnalyzeSubtitlesRequest: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "1.0";
            /** Sourcelanguage */
            sourceLanguage: string;
            /** Targetlanguage */
            targetLanguage: string;
            /** Cues */
            cues: components["schemas"]["SubtitleCueRequest"][];
        };
        /** AnalyzeSubtitlesResponse */
        AnalyzeSubtitlesResponse: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "1.0";
            /** Analysisid */
            analysisId: string;
            /** Sourcelanguage */
            sourceLanguage: string;
            /** Targetlanguage */
            targetLanguage: string;
            provider: components["schemas"]["ProviderResponse"];
            /** Cues */
            cues: components["schemas"]["CueAnalysisResponse"][];
        };
        /** CueAnalysisResponse */
        CueAnalysisResponse: {
            /** Cueid */
            cueId: string;
            /** Sourcetext */
            sourceText: string;
            /** Translations */
            translations: components["schemas"]["TranslationCandidateResponse"][];
            /** Segments */
            segments?: components["schemas"]["SegmentAnalysisResponse"][];
        };
        /** GrammaticalFeatureResponse */
        GrammaticalFeatureResponse: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** ProviderResponse */
        ProviderResponse: {
            /** Name */
            name: string;
            /** Model */
            model?: string | null;
            /** Revision */
            revision?: string | null;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Provider */
            provider: string;
        };
        /** ScriptVariantResponse */
        ScriptVariantResponse: {
            /** Script */
            script: string;
            /** Text */
            text: string;
        };
        /** SegmentAnalysisResponse */
        SegmentAnalysisResponse: {
            /** Segmentid */
            segmentId: string;
            /** Surface */
            surface: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "word" | "expression" | "punctuation" | "whitespace";
            /** Normalizedform */
            normalizedForm?: string | null;
            /** Romanization */
            romanization?: string | null;
            /** Scriptvariants */
            scriptVariants?: components["schemas"]["ScriptVariantResponse"][];
            /** Translations */
            translations?: components["schemas"]["TranslationCandidateResponse"][];
            /** Grammar */
            grammar?: components["schemas"]["GrammaticalFeatureResponse"][];
        };
        /** SubtitleCueRequest */
        SubtitleCueRequest: {
            /** Cueid */
            cueId: string;
            /** Text */
            text: string;
            /** Contextbefore */
            contextBefore?: string | null;
            /** Contextafter */
            contextAfter?: string | null;
        };
        /** TranslationCandidateResponse */
        TranslationCandidateResponse: {
            /** Text */
            text: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "contextual" | "literal";
            /** Isprimary */
            isPrimary: boolean;
            /** Confidence */
            confidence?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_subtitles_v1_subtitles_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeSubtitlesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeSubtitlesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
